### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ghost** [SimranPaul/Text-Detection-Vision#2]
@SimranPaul What does `text-vision.py` script do?

**Comment by SimranPaul** [comment]
Hi,

So, it uses Google Cloud Vision for text detection and recognition. After
which, I've used a python script to match the found text against a template
of label- value pairs. Once labels are found, it's vicinity( a range of
which can be set) is searched for data. The data once found is matched
against the regex in the template to improve accuracy. The label-data pairs
are then stored in JSON format to be used for other processing.
